name: Trigger auto deployment for gandhi-container-apper

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/gandhi-container-apper-AutoDeployTrigger-a2e33eaf-a52a-49ce-b8c8-e8c52ba7437b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GANDHICONTAINERAPPER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GANDHICONTAINERAPPER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GANDHICONTAINERAPPER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: gandhiserver.azurecr.io
          registryUsername: ${{ secrets.GANDHICONTAINERAPPER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GANDHICONTAINERAPPER_REGISTRY_PASSWORD }}
          containerAppName: gandhi-container-apper
          resourceGroup: gandhi-assignment3
          imageToBuild: gandhiserver.azurecr.io/gandhi-container-apper:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


